### ISSUE TITLE
UIDrawerController: Property automaticallyAddMenuButtonItems don't work as suggestion

### ISSUE THREAD

**Issue by hemangshah** [nathantannar4/SwiftMiniProjects#1]
> First of all great work on this project! I really like to learn how it's easy to write a drawer controller based on your code. Thank you.

Setting `automaticallyAddMenuButtonItems` to `false` still adding the menu buttons.

This is the code from Example project:

```
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {

        window = UIWindow(frame: UIScreen.main.bounds)
        
        let centerVC = UIViewController()
        centerVC.view.backgroundColor = .white
        
        let leftVC = UIViewController()
        leftVC.view.backgroundColor = .red
        
        let rightVC = UIViewController()
        rightVC.view.backgroundColor = .blue
        
        let drawer = UIDrawerController(centerViewController: UINavigationController(rootViewController: centerVC), leftViewController: leftVC, rightViewController: rightVC)
        drawer.automaticallyAddMenuButtonItems = false
        window?.rootViewController = drawer
        window?.makeKeyAndVisible()
        return true
    }
```

**Comment by hemangshah** [comment]
However, the setting `automaticallyAddMenuButtonItems` to `false`  actually not working at the time of initialization of `UIDrawerController`, it's working if I set it within the code it self.

**Comment by nathantannar4** [comment]
Thanks ill look at these when I have a moment! In the meantime try out some of my other controllers in https://github.com/nathantannar4/NTComponents

They are more refined

**Comment by hemangshah** [comment]
@nathantannar4 Thanks! Yes, sure I will try other controllers too. Would you please check out the other open issues as well?

**Comment by nathantannar4** [comment]
Fixed now
