### ISSUE TITLE
UIDrawerController: Showing a Gap when trying to pan the opened left or right view from the direction to close to open

### ISSUE THREAD

**Issue by hemangshah** [nathantannar4/SwiftMiniProjects#3]
A picture is a thousand words so here I am attaching a GIF file to help you understand the problem, your feedback is welcome.

![bothsides-gap](https://user-images.githubusercontent.com/3313412/31649942-c912880e-b332-11e7-8cd5-f16afcd3750b.gif)

**Comment by hemangshah** [comment]
If you set `isVisibleOnTop = false` then, you will not have this issue.

```
        drawer = UIDrawerController(centerViewController: UINavigationController(rootViewController: centerVC), leftViewController: leftVC, rightViewController: rightVC)
        drawer?.automaticallyAddMenuButtonItems = false
        var leftProperties = UIDrawerSideProperties.init(side: .left)
        leftProperties.isVisibleOnTop = false
        drawer?.leftViewProperties = leftProperties
        window?.rootViewController = drawer
```

**Comment by nathantannar4** [comment]
What you see there is actually a white view from `UIDrawerSideProperties.overflowView` 
You can change its color to anything you want to compensate for the stretching

**Comment by hemangshah** [comment]
Wow, thank you. This is helpful. 👍
